#!/usr/bin/env bash
# Render the per-tenant vhosts from BASE_DOMAIN + TLS_MODE.
#
#   TLS_MODE=none        -> plain HTTP on :80 (UNSECURED — testing only)
#   TLS_MODE=selfsigned  -> HTTPS :443 with a self-signed wildcard (dev)
#   TLS_MODE=byo|letsencrypt-*  -> HTTPS :443 with the mounted/issued wildcard
#
# Tenant labels contain no hyphen, so <tenant>.<base> and <tenant>-drive.<base>
# never collide (the SPA regex excludes hyphens; the WebDAV regex requires
# "-drive").
set -euo pipefail
BASE_DOMAIN="${BASE_DOMAIN:?BASE_DOMAIN required}"
TLS_MODE="${TLS_MODE:-selfsigned}"
CERT_DIR="${TLS_CERT_DIR:-/etc/nginx/tls}"
MAXBODY="${HTTP_MAX_BODY_BYTES:-0}"
BASE_RE="${BASE_DOMAIN//./\\.}"
OUT=/etc/nginx/conf.d/fileengine.conf

if [ "$TLS_MODE" = "none" ]; then
  LISTEN="listen 80;"
  SSL=""
  REDIRECT=""
else
  LISTEN="listen 443 ssl;
    http2 on;"
  SSL="ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;"
  REDIRECT="# HTTP -> HTTPS (and the ACME http-01 path, if ever used).
server {
    listen 80;
    server_name ~^.+\\.${BASE_RE}\$ ${BASE_DOMAIN};
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://\$host\$request_uri; }
}
"
fi

cat > "$OUT" <<EOF
# Generated by render-config.sh (BASE_DOMAIN=${BASE_DOMAIN}, TLS_MODE=${TLS_MODE}).
${REDIRECT}
# WebDAV: <tenant>-drive.<base> (matched first; labels contain no hyphen).
server {
    ${LISTEN}
    server_name ~^(?<tenant>[a-z0-9._]+)-drive\\.${BASE_RE}\$;
    ${SSL}
    client_max_body_size ${MAXBODY};
    include /etc/nginx/snippets/webdav.conf;
}

# Tenant SPA + same-origin /api, /csai, /mcp: <tenant>.<base>.
server {
    ${LISTEN}
    server_name ~^(?<tenant>[a-z0-9._]+)\\.${BASE_RE}\$;
    ${SSL}
    client_max_body_size ${MAXBODY};
    include /etc/nginx/snippets/tenant.conf;
}
EOF

echo "render-config: wrote $OUT (BASE_DOMAIN=${BASE_DOMAIN}, TLS_MODE=${TLS_MODE})"
